version: "3.9"

services:
  backend:
    build:
      context: ./backend        
      dockerfile: Dockerfile
    container_name: my-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo  
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend
    ports:
      - "5173:5173"

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: my-admin
    ports:
      - "5174:5173"

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

