name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Admin-Docker image
        run: docker build -t ci-cd-admin ./admin

      - name: Build Backend-Docker image
        run: docker build -t ci-cd-backend ./backend

      - name: Build Frontend-Docker image
        run: docker build -t ci-cd-frontend ./frontend

